name = "FreeTBX"
version = "0.1.0"
license = "license"
author = "nnardoto"
maintainer = "nnardoto@gmail.com"
copyright = "Copyright 2024, nnardoto"
[build]
external-modules = ["stdlib_linalg"]
link = ["fortran_stdlib"]
[library]
include-dir = "../..//Libraries/include/fortran_stdlib/GNU-13.2.0"
[dependencies]
libfdf.git = "https://gitlab.com/nnardoto/libfdf"
