name = "FreeTBX"
version = "0.1.0"
license = "license"
author = "nnardoto"
maintainer = "nnardoto@gmail.com"
copyright = "Copyright 2024, nnardoto"
[dependencies]
libfdf.git    = "https://gitlab.com/nnardoto/libfdf"
TermTools.git = "https://github.com/nnardoto/TermTools"
mfi           = { git="https://github.com/14NGiestas/mfi.git", branch="mfi-fpm" }
openmp        = "*" 
